const data = {
  products: [
    {
      name: "Shirt One",
      slug: "shirt-one",
      category: "Shirts",
      image: "/images/shirtone.jpeg",
      price: 4.99,
      brand: "Basic",
      rating: 5,
      numReviews: 8,
      countInStock: 20,
      description: "A basic shirt.",
      isFeatured: true,
      banner: "/images/banner1.jpg",
    },
    {
      name: "Shirt Two",
      slug: "shirt-two",
      category: "Shirts",
      image: "/images/shirttwo.webp",
      price: 9.99,
      brand: "Basic",
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: "A basic shirt.",
      isFeatured: true,
      banner: "/images/banner1.jpg",
    },
    {
      name: "Shirt Three",
      slug: "shirt-three",
      category: "Shirts",
      image: "/images/shirtthree.webp",
      price: 14.99,
      brand: "Basic",
      rating: 10,
      numReviews: 8,
      countInStock: 20,
      description: "A basic shirt.",
      isFeatured: true,
      banner: "/images/banner1.jpg",
    },
    {
      name: "Pants One",
      slug: "pants-one",
      category: "Shirts",
      image: "/images/pants1.jpeg",
      price: 4.99,
      brand: "Pants",
      rating: 5,
      numReviews: 8,
      countInStock: 20,
      description: "A basic pair of pants.",
      isFeatured: true,
      banner: "/images/banner2.webp",
    },
    {
      name: "Pants Two",
      slug: "pants-two",
      category: "Pants",
      image: "/images/pants2.jpeg",
      price: 9.99,
      brand: "Basic",
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: "A basic pair of pants.",
      isFeatured: true,
      banner: "/images/banner2.webp",
    },
    {
      name: "Pants Three",
      slug: "pants-three",
      category: "Pants",
      image: "/images/pants3.jpeg",
      price: 14.99,
      brand: "Basic",
      rating: 10,
      numReviews: 8,
      countInStock: 20,
      description: "A basic pair of pants.",
      isFeatured: true,
      banner: "/images/banner2.webp",
    },
  ],
};

export default data;
